# Generated by Django 2.2 on 2020-03-27 04:35

from django.db import migrations

from schools.factories import SchoolFactory
from students.factories import StudentFactory


def insert_school_student_data(apps, _):
    schools = SchoolFactory.create_batch(5)
    _ = [
        StudentFactory.create_batch(5, school=school)
        for school in schools
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            insert_school_student_data,
            migrations.RunPython.noop
        )
    ]
