# Generated by Django 2.2 on 2020-03-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200327_0435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id']},
        ),
    ]
