site_name: School Management API
site_description: API for handling records of schools and students
repo_url: https://github.com/nikkomidoy/school-management-api
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/nikkomidoy">nikkomidoy</a>.
dev_addr: 0.0.0.0:8001

nav:
    -   Home: 'index.md'
    -   API:
            -   Authentication: 'api/authentication.md'
            -   Users: 'api/users.md'
            -   Schools: 'api/schools.md'
            -   Students: 'api/students.md'
